export const dmeStats = {
  totalItems: 22,
  inUse: 16,
  underMaintenance: 2,
  totalAssetValue: 12930,
};

export const dmeItems = [
  {
    id: 1,
    name: "Hoyer Lift",
    category: "Mobility",
    assetTag: "EQ-1042",
    qtyInUse: 2,
    qtyTotal: 3,
    status: "In Service",
    assignedTo: "Multiple",
    unitValue: 4200,
  },
  {
    id: 2,
    name: "Wheelchair (Bariatric)",
    category: "Mobility",
    assetTag: "EQ-1077",
    qtyInUse: 1,
    qtyTotal: 1,
    status: "In Service",
    assignedTo: "Robert Hayes",
    unitValue: 2800,
  },
  {
    id: 3,
    name: "Hospital Bed — Electric",
    category: "Positioning",
    assetTag: "EQ-0995",
    qtyInUse: 5,
    qtyTotal: 6,
    status: "In Service",
    assignedTo: "Multiple",
    unitValue: 3600,
  },
  {
    id: 4,
    name: "Oxygen Concentrator",
    category: "Respiratory",
    assetTag: "EQ-1140",
    qtyInUse: 3,
    qtyTotal: 4,
    status: "Under Maintenance",
    assignedTo: "—",
    unitValue: 1950,
  },
  {
    id: 5,
    name: "Walker — Standard",
    category: "Mobility",
    assetTag: "EQ-0810",
    qtyInUse: 6,
    qtyTotal: 8,
    status: "In Service",
    assignedTo: "Multiple",
    unitValue: 180,
  },
];

export const consumableSupplies = [
  {
    id: 1,
    name: "Incontinence Briefs (L)",
    category: "Incontinence",
    stockOnHand: "340 units",
    reorderThreshold: "200 units",
    unitCost: "$0.85/unit",
    privatePayRate: "$1.20/unit",
    status: "OK",
  },
  {
    id: 2,
    name: "Wound Dressing 4x4",
    category: "Wound Care",
    stockOnHand: "45 boxes",
    reorderThreshold: "60 boxes",
    unitCost: "$6.20/box",
    privatePayRate: "$8.50/box",
    status: "Low Stock",
  },
  {
    id: 3,
    name: "Nitrile Gloves (M)",
    category: "PPE",
    stockOnHand: "1,200 pairs",
    reorderThreshold: "500 pairs",
    unitCost: "$0.12/pair",
    privatePayRate: "$0.20/pair",
    status: "OK",
  },
  {
    id: 4,
    name: "Nutritional Suppl. (Vanilla)",
    category: "Nutrition",
    stockOnHand: "80 cases",
    reorderThreshold: "40 cases",
    unitCost: "$18.50/case",
    privatePayRate: "$24.00/case",
    status: "OK",
  },
];

export const holidayWarning =
  "Upcoming Holiday: Wound Dressing 4x4 refill (Low Stock) falls within 2 days of Cesar Chavez Day — order early.";
